package gov.iti.jets;
// Generated Jan 10, 2023, 4:08:03 PM by Hibernate Tools 6.0.0.Alpha2

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Teacher generated by hbm2java
 */
@Entity
@DiscriminatorValue("TR")
@Table(name = "teacher", catalog = "inheritance2")
public class Teacher extends Person {

    private Date hireDate;

    public Teacher() {
    }

    public Teacher(Date hireDate) {
        this.hireDate = hireDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "hire_date", nullable = false, length = 10)
    public Date getHireDate() {
        return this.hireDate;
    }

    public void setHireDate(Date hireDate) {
        this.hireDate = hireDate;
    }

}
